### ISSUE TITLE
nie zerujesze wartości pArraySize

### ISSUE THREAD

**Issue by Masterpc96** [vol24pl/ZMPO-Lista01-Zadanie02#1]
https://github.com/vol24pl/ZMPO-Lista01-Zadanie02/blob/4401f5992ca67223c29f8dc35c04d00415c4a5a1/ZMPO-Lista01-Zadanie02/CircularQueue.cpp#L40

**Comment by vol24pl** [comment]
W tej metodzie obiekt przenoszony ma zostać przywrócony do "stanu bazowego".  Stan bazowy obiektu, to taki sam jak "swieżo" po stworzeniu obiektu, czyli:

- ma wyzerowane readNode
- ma wyzerowane writeNode 
- ma wyzerowane numberOfElements. 
- "świeży" obiekt ma sizeOfArray ustalony przy tworzeniu (niekoniecznie "0"). Przywrócenie obiektu do stanu "świeżego" nie zmienia tego parametru.
- ma również pustą listę o rozmiarze sizeOfArray (43 linijka kodu)

zamykam ticket.

**Comment by vol24pl** [comment]
Wg. prowadzącego obiekt taki **nie musi zostać przywrócony do stanu bazowego** ponieważ "umowa"(?) jest taka, że obiekt który został przeniesiony nie będzie już powtórnie używany.

W związku z tym zerowanie zmiennych bądź ich niezerowanie jest drugorzędne (prowadzący kurs zasugerował zerowanie). Najważniejsze to usunąć z obiektu przenoszone wskaźniki (ustawić je na nullptr), tak by zostały one tylko w nowym obiekcie.

Poprawka w commit'cie: https://github.com/vol24pl/ZMPO-Lista01-Zadanie02/commit/ecee1809346b896a439648d39bad75f7e34a4e12
